
services:
  backend:
    build: ./backend
    container_name: backend_server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "50051:50051"
    networks:
      - prisma-network
      - queue-network
    stdin_open: true
    tty: true
    depends_on:
      task_database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}"]
      interval: 1m30s
      timeout: 3s
      retries: 5
      start_period: 15s
  
  task_database:
    image: postgres:15
    hostname: task_database
    container_name: task_database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - queue-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  prisma-network:
  queue-network:

volumes:
  postgres_data: